version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "fix(security)"
    open-pull-requests-limit: 5
    automerge: true
    security-updates: true